"""p0 world model

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 01:41:48.643624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scenario_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', name='versionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('ontology_version', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['scenario_versions.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'number')
    )
    with op.batch_alter_table('scenario_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_versions_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('simulations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulations_version_id'), ['version_id'], unique=False)

    op.create_table('source_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('redacted_text', sa.Text(), nullable=False),
    sa.Column('redaction_map', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_version_id'), ['version_id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('ORGANISATION', 'AGENT', 'ASSET', 'VEHICLE', 'FACILITY', 'LOCATION', 'COMMODITY', 'INVENTORY', 'CONTRACT', 'POLICY', 'CHANNEL', 'EVENT', name='entitykind', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False, length=16), nullable=False),
    sa.Column('provenance', sa.Enum('F0', 'F1', 'A0', 'A1', 'S0', 'I0', 'P0', 'U0', name='provenance', native_enum=False, length=4), nullable=False),
    sa.Column('origin', sa.Enum('LLM', 'HUMAN', 'FIXTURE', 'ENGINE', name='origin', native_enum=False, length=16), nullable=False),
    sa.Column('source_document_id', sa.String(length=32), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'key')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_version_id'), ['version_id'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False, length=16), nullable=False),
    sa.Column('provenance', sa.Enum('F0', 'F1', 'A0', 'A1', 'S0', 'I0', 'P0', 'U0', name='provenance', native_enum=False, length=4), nullable=False),
    sa.Column('origin', sa.Enum('LLM', 'HUMAN', 'FIXTURE', 'ENGINE', name='origin', native_enum=False, length=16), nullable=False),
    sa.Column('source_document_id', sa.String(length=32), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'key')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_version_id'), ['version_id'], unique=False)

    op.create_table('agent_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('objectives', sa.JSON(), nullable=False),
    sa.Column('incentives', sa.JSON(), nullable=False),
    sa.Column('authority', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('decision_style', sa.String(length=200), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False, length=16), nullable=False),
    sa.Column('provenance', sa.Enum('F0', 'F1', 'A0', 'A1', 'S0', 'I0', 'P0', 'U0', name='provenance', native_enum=False, length=4), nullable=False),
    sa.Column('origin', sa.Enum('LLM', 'HUMAN', 'FIXTURE', 'ENGINE', name='origin', native_enum=False, length=16), nullable=False),
    sa.Column('source_document_id', sa.String(length=32), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    with op.batch_alter_table('agent_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_profiles_version_id'), ['version_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('actor_entity_id', sa.String(length=32), nullable=True),
    sa.Column('action_type', sa.String(length=60), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Enum('F0', 'F1', 'A0', 'A1', 'S0', 'I0', 'P0', 'U0', name='provenance', native_enum=False, length=4), nullable=False),
    sa.Column('caused_by_event_id', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['caused_by_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'seq')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('review_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False, length=16), nullable=False),
    sa.Column('provenance', sa.Enum('F0', 'F1', 'A0', 'A1', 'S0', 'I0', 'P0', 'U0', name='provenance', native_enum=False, length=4), nullable=False),
    sa.Column('origin', sa.Enum('LLM', 'HUMAN', 'FIXTURE', 'ENGINE', name='origin', native_enum=False, length=16), nullable=False),
    sa.Column('source_document_id', sa.String(length=32), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'entity_id', 'attribute')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_version_id'), ['version_id'], unique=False)

    op.create_table('initial_knowledge',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('agent_entity_id', sa.String(length=32), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=32), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('kind', sa.Enum('KNOWS', 'BELIEVES', name='knowledgekind', native_enum=False, length=16), nullable=False),
    sa.Column('review_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False, length=16), nullable=False),
    sa.Column('provenance', sa.Enum('F0', 'F1', 'A0', 'A1', 'S0', 'I0', 'P0', 'U0', name='provenance', native_enum=False, length=4), nullable=False),
    sa.Column('origin', sa.Enum('LLM', 'HUMAN', 'FIXTURE', 'ENGINE', name='origin', native_enum=False, length=16), nullable=False),
    sa.Column('source_document_id', sa.String(length=32), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('initial_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_initial_knowledge_agent_entity_id'), ['agent_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_initial_knowledge_version_id'), ['version_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False, length=16), nullable=False),
    sa.Column('provenance', sa.Enum('F0', 'F1', 'A0', 'A1', 'S0', 'I0', 'P0', 'U0', name='provenance', native_enum=False, length=4), nullable=False),
    sa.Column('origin', sa.Enum('LLM', 'HUMAN', 'FIXTURE', 'ENGINE', name='origin', native_enum=False, length=16), nullable=False),
    sa.Column('source_document_id', sa.String(length=32), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_version_id'), ['version_id'], unique=False)

    op.create_table('knowledge_updates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('agent_entity_id', sa.String(length=32), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=32), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('kind', sa.Enum('KNOWS', 'BELIEVES', name='knowledgekind', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['agent_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_updates_agent_entity_id'), ['agent_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_updates_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('state_changes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=False),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('state_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_changes_simulation_id'), ['simulation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_changes_simulation_id'))

    op.drop_table('state_changes')
    with op.batch_alter_table('knowledge_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_updates_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_updates_agent_entity_id'))

    op.drop_table('knowledge_updates')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_version_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_target_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_source_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('initial_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_initial_knowledge_version_id'))
        batch_op.drop_index(batch_op.f('ix_initial_knowledge_agent_entity_id'))

    op.drop_table('initial_knowledge')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_version_id'))
        batch_op.drop_index(batch_op.f('ix_facts_entity_id'))

    op.drop_table('facts')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_simulation_id'))

    op.drop_table('events')
    with op.batch_alter_table('agent_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_profiles_version_id'))

    op.drop_table('agent_profiles')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_version_id'))

    op.drop_table('rules')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_version_id'))

    op.drop_table('entities')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_version_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_version_id'))

    op.drop_table('simulations')
    with op.batch_alter_table('scenario_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_versions_scenario_id'))

    op.drop_table('scenario_versions')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
