"""injections and run continuation

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 17:35:22.021392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('redacted_text', sa.Text(), nullable=False),
    sa.Column('redaction_map', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injections_version_id'), ['version_id'], unique=False)

    op.create_table('injection_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('injection_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False, length=16), nullable=False),
    sa.Column('origin', sa.Enum('LLM', 'HUMAN', 'FIXTURE', 'ENGINE', name='origin', native_enum=False, length=16), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=True),
    sa.Column('auto_accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['injection_id'], ['injections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injection_items_injection_id'), ['injection_id'], unique=False)

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('injection_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_entities_injection_id'), ['injection_id'], unique=False)
        batch_op.create_foreign_key('fk_entities_injection_id', 'injections', ['injection_id'], ['id'])

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('fork_round', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('injection_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_simulations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_simulations_parent_id', 'simulations', ['parent_id'], ['id'])
        batch_op.create_foreign_key('fk_simulations_injection_id', 'injections', ['injection_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_simulations_parent_id', type_='foreignkey')
        batch_op.drop_constraint('fk_simulations_injection_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_simulations_parent_id'))
        batch_op.drop_column('injection_id')
        batch_op.drop_column('fork_round')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_entities_injection_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_entities_injection_id'))
        batch_op.drop_column('injection_id')

    with op.batch_alter_table('injection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injection_items_injection_id'))

    op.drop_table('injection_items')
    with op.batch_alter_table('injections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injections_version_id'))

    op.drop_table('injections')
    # ### end Alembic commands ###
